import React from 'react'
import { Calendar, MapPin, User, Share2, Lock } from 'lucide-react'
import IncidentLogEntry from './IncidentLogEntry'

const IncidentLog = ({ incidents, onPremiumFeature }) => {
  const generateSummary = (incident) => {
    if (!onPremiumFeature()) return
    
    const summary = `Incident Report - ${new Date(incident.timestamp).toLocaleDateString()}
    
Location: ${incident.location || 'Not specified'}
Officer Details: ${incident.officerDetails || 'Not provided'}
Summary: ${incident.interactionSummary}

Generated by RightGuard AI - Know your rights, anytime, anywhere.`
    
    // In a real app, this would use the Web Share API or copy to clipboard
    if (navigator.share) {
      navigator.share({
        title: 'Incident Report',
        text: summary
      })
    } else {
      navigator.clipboard.writeText(summary)
      alert('Summary copied to clipboard')
    }
  }

  return (
    <div className="container py-lg space-y-lg">
      <div className="flex items-center justify-between">
        <h1 className="text-heading1">Incident Log</h1>
        <div className="text-caption text-text-secondary">
          {incidents.length} incidents logged
        </div>
      </div>

      {incidents.length === 0 ? (
        <div className="card text-center py-xl">
          <div className="space-y-md">
            <div className="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mx-auto">
              <Calendar className="h-8 w-8 text-text-secondary" />
            </div>
            <h3 className="text-heading2">No incidents logged yet</h3>
            <p className="text-body text-text-secondary max-w-md mx-auto">
              When you log an incident from the Record tab, it will appear here for future reference.
            </p>
          </div>
        </div>
      ) : (
        <div className="space-y-md">
          {incidents.map((incident) => (
            <IncidentLogEntry
              key={incident.id}
              incident={incident}
              onShare={() => generateSummary(incident)}
              canShare={onPremiumFeature()}
            />
          ))}
        </div>
      )}

      {/* Premium Features */}
      <div className="card bg-primary/5 border border-primary/20">
        <div className="flex items-start space-x-3">
          <Lock className="h-6 w-6 text-primary flex-shrink-0 mt-1" />
          <div>
            <h3 className="text-heading2 text-primary mb-sm">Premium Log Features</h3>
            <ul className="text-body text-text-secondary space-y-1 mb-md">
              <li>• Unlimited incident storage</li>
              <li>• Generate shareable summaries</li>
              <li>• Export to legal professionals</li>
              <li>• Encrypted cloud backup</li>
            </ul>
            <button
              onClick={onPremiumFeature}
              className="btn-primary"
            >
              Upgrade to Premium
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}

export default IncidentLog